### ISSUE TITLE
Exception in thread "main" java.lang.IllegalAccessError

### ISSUE THREAD

**Issue by cybernetics** [kawasima/try-artifact#3]
> javac -version
javac 9-ea

> java -version
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+131)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+131, mixed mode)

> java -jar try-artifact-0.1.2.jar
Exception in thread "main" java.lang.IllegalAccessError: tried to access field jdk.jshell.SourceCodeAnalysis$CompletionInfo.completeness from class net.unit8.erebus.tryartifact.tool.TryJShellTool
        at net.unit8.erebus.tryartifact.tool.TryJShellTool.processSource(TryJShellTool.java:1877)
        at net.unit8.erebus.tryartifact.tool.TryJShellTool.processSourceCatchingReset(TryJShellTool.java:614)
        at net.unit8.erebus.tryartifact.tool.TryJShellTool.run(TryJShellTool.java:594)
        at net.unit8.erebus.tryartifact.tool.TryJShellTool.resetState(TryJShellTool.java:531)
        at net.unit8.erebus.tryartifact.tool.TryJShellTool.start(TryJShellTool.java:367)
        at net.unit8.erebus.tryartifact.tool.TryJShellTool.start(TryJShellTool.java:362)
        at net.unit8.erebus.TryArtifact.main(TryArtifact.java:17)

**Comment by kawasima** [comment]
Thank you for your report.
I fixed the compatibility problem in the [version 0.2.0](https://github.com/kawasima/try-artifact/releases/tag/v0.2.0).
