### ISSUE TITLE
Exception in thread "main" java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by cybernetics** [kawasima/try-artifact#5]
>javac -version
javac 9-ea

>java -version
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+136)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+136, mixed mode)

>java -jar try-artifact-0.2.0.jar
Exception in thread "main" java.lang.IncompatibleClassChangeError: Found interface jdk.jshell.SourceCodeAnalysis$CompletionInfo, but class was expected
        at net.unit8.erebus.tryartifact.tool.TryJShellTool.processSource(TryJShellTool.java:1877)
        at net.unit8.erebus.tryartifact.tool.TryJShellTool.processSourceCatchingReset(TryJShellTool.java:614)
        at net.unit8.erebus.tryartifact.tool.TryJShellTool.run(TryJShellTool.java:594)
        at net.unit8.erebus.tryartifact.tool.TryJShellTool.resetState(TryJShellTool.java:531)
        at net.unit8.erebus.tryartifact.tool.TryJShellTool.start(TryJShellTool.java:367)
        at net.unit8.erebus.tryartifact.tool.TryJShellTool.start(TryJShellTool.java:362)
        at net.unit8.erebus.TryArtifact.main(TryArtifact.java:17)

**Comment by bhagatsingh** [comment]
**Same problem here.**
Java Version: **build 9-ea+153-jigsaw-nightly-h6003-20170124**
OS: **Windows 10**

$.\jdk-9\bin\java -jar try-artifact-0.2.0.jar

Exception in thread "main" java.lang.IncompatibleClassChangeError: Found interface jdk.jshell.SourceCodeAnalysis$CompletionInfo, but class was expected
        at net.unit8.erebus.tryartifact.tool.TryJShellTool.processSource(TryJShellTool.java:1877)
        at net.unit8.erebus.tryartifact.tool.TryJShellTool.processSourceCatchingReset(TryJShellTool.java:614)
        at net.unit8.erebus.tryartifact.tool.TryJShellTool.run(TryJShellTool.java:594)
        at net.unit8.erebus.tryartifact.tool.TryJShellTool.resetState(TryJShellTool.java:531)
        at net.unit8.erebus.tryartifact.tool.TryJShellTool.start(TryJShellTool.java:367)
        at net.unit8.erebus.tryartifact.tool.TryJShellTool.start(TryJShellTool.java:362)
        at net.unit8.erebus.TryArtifact.main(TryArtifact.java:17)

**Comment by bhagatsingh** [comment]
I have fixed **" java.lang.IncompatibleClassChangeError"** exception and you can find the modified code at [try-artifact](https://github.com/bhagatsingh/try-artifact.git)
